### ISSUE TITLE
Is resample() expected to work on an element outside the DOM?

### ISSUE THREAD

**Issue by nareshbhatia** [viliusle/Hermite-resize#10]
I am using Hermite-resize along with [react-avatar-editor](https://github.com/mosch/react-avatar-editor). After editing my image in react-avatar-editor, it returns the image to me as a free-standing HTMLCanvasElement (not in the DOM). Now when I try to resize the canvas using Hermite-resize, I am getting a blank image. Is this expected to work?

Here's the code that react-avatar-editor uses to give me a canvas (original code [here](https://github.com/mosch/react-avatar-editor/blob/master/src/index.js#L210-L250)):

    getImage () {
        const canvas = document.createElement('canvas')
        const context = canvas.getContext('2d')

        ...

        context.drawImage(image.resource, -cropRect.x, -cropRect.y)
        return canvas
    }

After getting this canvas, here's how I am passing it to Hermite-resize:

    const HERMITE = new Hermite_class();
    HERMITE.resample(canvas, 1024, 1024);

Finally when I save this canvas to a file. I get a blank image in the file. Just as a check, if I don't pass the canvas through Hermite-resize, I get the expected image in the file (without resizing).

Thanks in advance for your help.

**Comment by viliusle** [comment]
Hermite_class does not use DOM, it should work. 
Try using HERMITE.resample_single(canvas, 1024, 1024);

**Comment by nareshbhatia** [comment]
Hi @viliusle, I tried `HERMITE.resample_single(canvas, 1024, 1024);` on a PNG file of size 1437x1437. It is now resizing the image, however there are two issues:

1. The resized image is 770x770 instead of 1024x1024
2. The image is not cropped at all. In other words, the size of the canvas is still 1437x1437. The reduced image is simply sitting in the top-left corner of this canvas.

**Comment by viliusle** [comment]
HERMITE.resample_single(canvas, 1024, 1024, true) will resize canvas, it is off by default (will change it to on by default.) 

Also your canvas is probably translated (ctx.translate), so it resized to 770, not 1024. Does it has white area?

p.s. this function does not resize visible area, it resize all canvas.

**Comment by nareshbhatia** [comment]
Aha, did not know about the resize flag, I will try it out. Will also check if the canvas was translated in the image that I tried this with. The react-avatar-editor does allow translation, so that could be the issue. Thanks for all your help!
