### ISSUE TITLE
NPM

### ISSUE THREAD

**Issue by mrjumpy** [viliusle/Hermite-resize#2]
your npm is out of date.
can u update to this repo? thanks

and

`block_height` and `offset_y`
duplicate defined. 
maybe can use eslint check code?

**Comment by viliusle** [comment]
Somebody else registered it in npm. I will see what i can do.

p.s. duplicate fixed.

**Comment by viliusle** [comment]
Command below works now:

npm install viliusle/Hermite-resize

**Comment by viliusle** [comment]
OK, issue should be fixed now. Command below works:

npm install https://github.com/viliusle/Hermite-resize.git
