### ISSUE TITLE
Scaling down image quality

### ISSUE THREAD

**Issue by FarSeeing** [viliusle/Hermite-resize#5]
Hi. First of all, thank you for your library - really nice thing we're using.
The only issue we've stumbled upon: downscaled images get worse quality compared to scaling them manually with some editor:
http://i.imgur.com/3aGzDeO.jpg - original image,
http://i.imgur.com/ttvCh77.jpg - scaled w/library,
http://i.imgur.com/tvljveN.jpg - scaled manually.
It's not a critical difference but could you please take a look? Many thanks in advance.

**Comment by viliusle** [comment]
Please repeat  your test using single core version (resample_single). Multi core version has some advantages, but it also has minor issues because of splitting image and combining. This way i get better result and it is very close to your manual resized version.

**Comment by FarSeeing** [comment]
Thanks for your reply. Single core version resulted in http://i.imgur.com/o72reQl.jpg
Anything else I can do to increase the quality?

**Comment by viliusle** [comment]
Quality is not bad, what problem do you see exactly? 
If you want to increase quality even more, apply minimal sharpen effect, it gives nice effect.
