### ISSUE TITLE
Uncaught TypeError: on_finish is not a function

### ISSUE THREAD

**Issue by lyltj2010** [viliusle/Hermite-resize#6]
when I use this library, i got this [Uncaught TypeError: on_finish is not a function](https://github.com/viliusle/Hermite-resize/blob/1126997d772a2d005e5dc30d2e818c905539b5b9/src/hermite.js#L46) error. Is there anything I can do with it to remove this error?

**Comment by viliusle** [comment]
This param must be finish handler (function), but it is optional, and code required it...
Fixed in latest version.

**Comment by lyltj2010** [comment]
thanks.
