### ISSUE TITLE
Change package name to lowercase

### ISSUE THREAD

**Issue by FarSeeing** [viliusle/Hermite-resize#7]
In current `package.json` file package is named `Hermite-resize`. Could you please change it to `hermite-resize`? This is the proposed behavior for npm packages:

Extract from https://docs.npmjs.com/getting-started/using-a-package.json#requirements
> "name"
> all lowercase

Moreover, some node/npm features like requiring package just won't work unless package name is all lowercase.

**Comment by viliusle** [comment]
package.json name updated, npm install command works.

**Comment by FarSeeing** [comment]
Thanks, closing issue.
