### ISSUE TITLE
How do I contribute?

### ISSUE THREAD

**Issue by OACDesigns** [viliusle/Hermite-resize#9]
Hi
I have found a couple of bugs and created fixes for them.
I've created a pull request (https://github.com/viliusle/Hermite-resize/pull/8), however do you have a preferred process? 
Should I create the dist. versions as well, and if so, how can I go about building them?

Thanks,
Oisin

**Comment by viliusle** [comment]
i need to automate building. Will try to do that in next few days. You can ignore dist and versions.

**Comment by OACDesigns** [comment]
ok cool, in that case the PR should be fine to merge whenever you're ready.
Let me know if you would also like more details about the PR. 

Thanks,
Oisin
